name: PlateTialsUI
version: 1.0
main: BabosAppol\PlateTialsUI\Main
api: 3.0.0

commands:
  heal:
    description: "Set your health or other people heart"
  feed:
    description: "Set your food or other people food"
  clear:
    description: "Clear other people inventory/armours/effects or yourself"
